### ISSUE TITLE
Removing a paper still assigned in screening

### ISSUE THREAD

**Issue by esyriani** [geodes-sms/relis#33] opened 2021-03-08 13:00 UTC
**Describe the bug**
I first assign a paper to a reviewer for screening. Then I remove the paper. The paper still appears in the the list of the reviewer to screen.

**To Reproduce**
1. Import or manually add a paper. Suppose the bibtexKey is ABC
2. Go to Screening. Assign papers. Assign it to me.
3. Go to Screening. Screen. The paper shows up.
4. Go to Papers > All. Search for ABC. Click on Delete to remove it. It is correctly removed from all the lists under Paper (All, Included, Excluded, Pending)
5. Go to Screening. Screen. The paper still shows up.
6. Go to Statistics. The numbers have not changed.

**Expected behavior**
In ReLiS, deleting a paper doesn't actually remove it, but deactivates it. When a paper is deactivated, it should not appear anymore in any list: screening, statistics, classification, authors, venues, etc.

**Screenshots**
For example, you can go to the project Language Composition. Paper Qiao2020_3 is deactivated but still shows up in Naima's screening.
Actually, if you run the following query:
```sql
SELECT count(*)
FROM paper
INNER JOIN screening_paper ON screening_paper.paper_id = paper.id
WHERE paper.paper_active=0 and screening_paper.screening_active=1
```
You should always get 0, but here you get 22. When paper_active=0, screening_active should also =0. I think you must also have classification.class_active=0. The views in the statistics should also take the active status into consideration.

**Comment by PUR2212** [comment] 2021-08-15 12:49
duplicate of issue #37

**Closed** 2022-05-16 09:39 UTC
Labels: bug, duplicate
